_BASE_: "MESH-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "meshrcnn://coco_init_0719.pth" # "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  VOXEL_ON: False
  MESH_ON: False
  ZPRED_ON: False
  OCC_ON: True
  RESNETS:
    DEPTH: 50
#    RES2_OUT_CHANNELS: 64
  RPN:
    IOU_THRESHOLDS: [0.2, 0.5, 0.7]
    IOU_LABELS: [-1, 0, -1, 1]
    SMOOTH_L1_BETA: 0.111
  ROI_HEADS:
    NAME: "MeshRCNNROIHeads"
    BATCH_SIZE_PER_IMAGE: 8
    NUM_CLASSES: 1 # Number of foreground classes
    IOU_THRESHOLDS: [0.2, 0.5]
    IOU_LABELS: [-1, 0, 1]
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 1.0
  ROI_Z_HEAD:
    NAME: "FastRCNNFCHead"
    Z_REG_WEIGHT: 1.0
    SMOOTH_L1_BETA: 1.0
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    NUM_CONV: 4
  ROI_VOXEL_HEAD:
    NAME: "VoxelRCNNConvUpsampleHead"
    POOLER_RESOLUTION: 12
    POOLER_SAMPLING_RATIO: 2
    NUM_CONV: 4
    NUM_DEPTH: 24
    CLS_AGNOSTIC_VOXEL: True
    LOSS_WEIGHT: 3.0
    CUBIFY_THRESH: 0.2
  ROI_MESH_HEAD:
    NAME: "MeshRCNNGraphConvHead"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    NUM_STAGES: 3
    NUM_GRAPH_CONVS: 3
    GRAPH_CONV_DIM: 128
    GRAPH_CONV_INIT: "normal"
    GT_COORD_THRESH: 5.0
    CHAMFER_LOSS_WEIGHT: 1.0
    NORMALS_LOSS_WEIGHT: 0.1
    EDGE_LOSS_WEIGHT: 1.0
  ROI_OCCNET_HEAD:
    NAME: "OccNetRCNNHead"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    LOSS_WEIGHT: 1.0
    CLS_AGNOSTIC_OCCUPANCY: True
    SAMPLED_POINTS_PER_ITERATION: 2048
DATASETS:
  TRAIN: ("shapenet_phones",)
  TEST: ("shapenet_phones",)
#  TRAIN: ("pix3d_s1_train_bookcase",)
#  TEST: ("pix3d_s1_test_bookcase",)
SOLVER:
#  BASE_LR: 0.001
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
#  STEPS: (32000, 40000)
#  MAX_ITER: 44000
#  WARMUP_ITERS: 4000
  STEPS: (320, 400)
  MAX_ITER: 440
  WARMUP_ITERS: 40
  WARMUP_FACTOR: 0.1
  #  IMS_PER_BATCH: 2
  IMS_PER_BATCH: 6
